# Generated by Django 5.1.4 on 2026-01-28 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assessments.teacherfeedback',),
        ),
        migrations.AlterModelOptions(
            name='aifeedback',
            options={'verbose_name': 'AI Feedback', 'verbose_name_plural': 'AI Feedback'},
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Assignment', 'verbose_name_plural': 'Assignments'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Submission', 'verbose_name_plural': 'Submissions'},
        ),
        migrations.AlterModelOptions(
            name='teacherfeedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Teacher Feedback', 'verbose_name_plural': 'Teacher Feedback'},
        ),
        migrations.AddField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aifeedback',
            name='feedback_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aifeedback',
            name='improvements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aifeedback',
            name='strengths',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aifeedback',
            name='suggestions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(help_text='Assignment questions or description'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='instructions',
            field=models.TextField(help_text='Detailed instructions for students'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='content',
            field=models.TextField(help_text="Student's answer/response"),
        ),
        migrations.AlterField(
            model_name='teacherfeedback',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_feedback_set', to='assessments.submission'),
        ),
        migrations.AlterField(
            model_name='teacherfeedback',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_feedback', to=settings.AUTH_USER_MODEL),
        ),
    ]
